= lake-data

Web application for maintaining lake water quality data for the Pipe Lake district

== Swagger UI
http://localhost:8081/swagger-ui/

== Characteristic Types
* EVENT: something that happens once a year for a specific characteristic.
* WATER: Something that happens once a day for a specific characteristic.

== TODO
* allow power users a read only view of the maintenance pages
** low priority. not sure of the need yet.
* Change reporter to user or administrator
* Add a district layer.
** Sites are part of a district
** Consider documents can be associated to a district
** Consider measurements can be at a district level
** Administration can be constrained to a district level
** Data entry can be constrained to a district level
** Board members are constrained to a district
* Get someone to add the other documents to the system
* Link documents to pipe lake web site
* Enhance the users to include more details to include property and plot maps and email capabilities.
* Add a new role for managing and contacting residents.
* Change style sheet to make site look more like the pipe lake site.
* Add help pages to all maintenance pages.
* Set up https://superset.apache.org/
* Create a mapping between event type characteristics and sites. This would create a characteristic_site table.
 This is analogous to the characteristic_location table. I do not want to do this. This would limit the
 events to a specific site for data entry.
* Bulk upload and download of documents. I do not want to do this. Will do as an on-demand request.
* Change the document storage to include other documents like excel and word docs.
** I do not want to do this. Reason is that PDF documents are not really editable.
** How would searching an Excel file work?
**  Purpose of document store is for informational documents about the lake. Excel documents can be saved as PDF

== Technologies Used:
* Groovy
* Spring Boot
* Spring JPA
* Spring Security
* MySQL
* ThymeLeaf
* JQuery
* Bootstrap
* js-grid for maintenance pages: http://js-grid.com/
* ChartJS: https://www.chartjs.org/
* style sheet: https://bootswatch.com/4/

Wisconsin DNR data site is https://dnrx.wisconsin.gov/swims/login.jsp

== PDF Design Thoughts
=== Lucine
Lucine is an open source indexing and search library for java

* https://nullbeans.com/spring-boot-and-lucene-configuration-example/
* https://wkrzywiec.medium.com/full-text-search-with-hibernate-search-lucene-part-1-e245b889aa8e
* https://dzone.com/articles/jpa-searching-using-lucene
* https://lucene.apache.org/index.html

=== PDF
Libraries for dealing with pdf or other types of documents. iText used to be the leading
library for this but is no longer free.

* https://pdfbox.apache.org/
* https://tika.apache.org/ All document types. Not limited to PDF.
* https://colwil.com/how-to-extract-text-from-a-scanned-pdf-using-ocr-in-java/

=== Solr
Is a complete open source system that uses lucine. Not needed currently

* https://solr.apache.org/

Larry's Example: https://optidat.com/pl/pipe-lakes-district-records-archive/

== Map Data Research
* https://polkcowi.wgxtreme.com/
* https://www.co.polk.wi.us/landinfoparcelmapping
* https://www.sco.wisc.edu/data/parcels/
* https://www.arcgis.com/apps/webappviewer/index.html?id=4ca7d1c99bb04e4aac8351e8fcb25897
* https://maps.sco.wisc.edu/Parcels/
* https://www.sco.wisc.edu/parcels/data/
* https://mapservices.legis.wisconsin.gov/arcgis/rest/services/WLIP
* https://www.co.polk.wi.us/landrecords
* https://www.co.polk.wi.us/landinfogisdataportal

== Administrator Maintenance
Thinking of adding the ability to better manage administrators.
First change reporter to administrator. Update the table names, foreign keys, and indexes. Update the menus and the ui and everything to have administrator instead of reporter.

Create a page for people to request to be administrators.

* A username, password, first name, last name, and email address will be required.
* The username cannot be an email address. It cannot already exist in the system.
* Ask what type of administrator they want to be
* Describe each type and what that means.
* The system will notify the other administrators and request for a review via email. The system will add the user into the system, but they will be disabled. Upon notification the administrator can choose to delete the user from the system or leave them disabled or enable them.
* Upon enabling the user, an email will be sent to the user notifying them they have been enabled.
* The administrator can choose to force the user to create a new password upon logging in.
* This page will be accessible from the login page only.

Add a new login page that allows users to request to be an administrator, change there password, forgot their password besides logging in.

Implement a password change process that will allow a user to change their password. The user will need to know their current password to do this.

Do I need a forgot username process? Yes. User will be required to enter their first name and last name and email address. The system will verify this data against what is stored and generate an email back to the user that contains their username.

Implement a forgot their password flow. The user will need to enter their username, first name, last name and email address. The system will validate all this data against what is stored. This process will send the user a new temporary password via email. Once the user logs in they will be required to change their password. A new boolean value will be added to the database to indicate if the person is required to change their password. The new temporary password will be generated randomly and saved in the password field and the force change attribute will be updated to true.

Update the administrator maintenance page to include the checkbox to force the password update.

Work todo:

* New page for requesting administrator access
* New dedicated login page
* New forgot username page
* New forgot password page
* New change password page
* New change_password attribute added to administrator table