spring:
  application:
    name: lake-data
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pipe_lake?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: lake_data_app
    password: Pa$$word8
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 15
      connection-init-sql: select 1
    tomcat:
      jmx-enabled: false
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
  groovy:
    template:
      check-template-location: false
ftp:
  upload-location: /home/lake-data-ftp/ftp/upload
  process-location: /home/lake-data-ftp/process
  archive-location: /home/lake-data-ftp/archive